# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: twopc.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'twopc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btwopc.proto\"%\n\nGetRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0b\n\x03key\x18\x02 \x01(\t\"\x1c\n\x0bGetResponse\x12\r\n\x05value\x18\x01 \x01(\x05\"4\n\nPutRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\x05\"\x1c\n\x0bPutResponse\x12\r\n\x05\x65mpty\x18\x01 \x01(\t\"3\n\x12\x43ommitQueryMessage\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\tcommit_id\x18\x02 \x01(\x05\"\"\n\x13\x43ommitQueryResponse\x12\x0b\n\x03\x61\x63k\x18\x01 \x01(\t\"\x1b\n\rCommitMessage\x12\n\n\x02id\x18\x01 \x01(\x05\"\x1d\n\x0e\x43ommitResponse\x12\x0b\n\x03\x61\x63k\x18\x01 \x01(\t2\xba\x01\n\x06Update\x12\"\n\x03Get\x12\x0b.GetRequest\x1a\x0c.GetResponse\"\x00\x12\"\n\x03Put\x12\x0b.PutRequest\x1a\x0c.PutResponse\"\x00\x12:\n\x0b\x43ommitQuery\x12\x13.CommitQueryMessage\x1a\x14.CommitQueryResponse\"\x00\x12,\n\x07\x43ommmit\x12\x0e.CommitMessage\x1a\x0f.CommitResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'twopc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETREQUEST']._serialized_start=15
  _globals['_GETREQUEST']._serialized_end=52
  _globals['_GETRESPONSE']._serialized_start=54
  _globals['_GETRESPONSE']._serialized_end=82
  _globals['_PUTREQUEST']._serialized_start=84
  _globals['_PUTREQUEST']._serialized_end=136
  _globals['_PUTRESPONSE']._serialized_start=138
  _globals['_PUTRESPONSE']._serialized_end=166
  _globals['_COMMITQUERYMESSAGE']._serialized_start=168
  _globals['_COMMITQUERYMESSAGE']._serialized_end=219
  _globals['_COMMITQUERYRESPONSE']._serialized_start=221
  _globals['_COMMITQUERYRESPONSE']._serialized_end=255
  _globals['_COMMITMESSAGE']._serialized_start=257
  _globals['_COMMITMESSAGE']._serialized_end=284
  _globals['_COMMITRESPONSE']._serialized_start=286
  _globals['_COMMITRESPONSE']._serialized_end=315
  _globals['_UPDATE']._serialized_start=318
  _globals['_UPDATE']._serialized_end=504
# @@protoc_insertion_point(module_scope)
